name: geoglows_ecflow
channels:
  - conda-forge
  - defaults
dependencies:
  - ecflow
  - nco
  - pyyaml
  - numpy
  - dask
  - pandas
  - fastparquet
  - xarray
  - netcdf4
  - zarr
  - boto3
  - pip:
    - basininflow @ git+https://pypi.org/project/basininflow/
    - RAPIDpy @ git+https://github.com/BYU-Hydroinformatics/RAPIDpy/
